# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.Qt import Qt


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(450, 618)
        mainWindow.setStyleSheet("background-color: rgb(64, 179, 191);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input = QtWidgets.QLabel(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(25, 10, 400, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.input.setFont(font)
        self.input.setStyleSheet("background-color: rgb(64, 191, 119);\n"
"border: 1px solid rgb(191, 172, 64);\n"
"border-radius: 5px;")
        self.input.setText("")
        self.input.setObjectName("input")
        self.btn_CE = QtWidgets.QPushButton(self.centralwidget)
        self.btn_CE.setGeometry(QtCore.QRect(25, 89, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_CE.setFont(font)
        self.btn_CE.setObjectName("btn_CE")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(125, 89, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(225, 89, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_mult.setFont(font)
        self.btn_mult.setObjectName("btn_mult")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(325, 89, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_sub.setFont(font)
        self.btn_sub.setObjectName("btn_sub")
        self.btn_sum = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sum.setGeometry(QtCore.QRect(325, 195, 95, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_sum.setFont(font)
        self.btn_sum.setObjectName("btn_sum")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(225, 195, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(25, 195, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(125, 195, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(125, 300, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(25, 300, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(225, 300, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(125, 406, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_result = QtWidgets.QPushButton(self.centralwidget)
        self.btn_result.setGeometry(QtCore.QRect(325, 406, 95, 197))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_result.setFont(font)
        self.btn_result.setObjectName("btn_result")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(25, 406, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(225, 406, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(25, 509, 195, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.btn_dot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dot.setGeometry(QtCore.QRect(225, 509, 95, 95))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_dot.setFont(font)
        self.btn_dot.setObjectName("btn_dot")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        #============================My Code=========================
        self.btn_0.clicked.connect(lambda: self.addParameter(0))
        self.btn_1.clicked.connect(lambda: self.addParameter(1))
        self.btn_2.clicked.connect(lambda: self.addParameter(2))
        self.btn_3.clicked.connect(lambda: self.addParameter(3))
        self.btn_4.clicked.connect(lambda: self.addParameter(4))
        self.btn_5.clicked.connect(lambda: self.addParameter(5))
        self.btn_6.clicked.connect(lambda: self.addParameter(6))
        self.btn_7.clicked.connect(lambda: self.addParameter(7))
        self.btn_8.clicked.connect(lambda: self.addParameter(8))
        self.btn_9.clicked.connect(lambda: self.addParameter(9))
        self.btn_div.clicked.connect(lambda: self.addParameter('/'))
        self.btn_mult.clicked.connect(lambda: self.addParameter('*'))
        self.btn_sub.clicked.connect(lambda: self.addParameter('-'))
        self.btn_sum.clicked.connect(lambda: self.addParameter('+'))
        self.btn_dot.clicked.connect(lambda: self.addParameter('.'))

        # CE btn
        self.btn_CE.clicked.connect(lambda: self.input.setText(''))

        # result
        self.btn_result.clicked.connect(self.result)

    
    #====================Designer Functions==========================
    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Calculator"))
        self.btn_CE.setText(_translate("mainWindow", "CE"))
        self.btn_div.setText(_translate("mainWindow", "/"))
        self.btn_mult.setText(_translate("mainWindow", "*"))
        self.btn_sub.setText(_translate("mainWindow", "-"))
        self.btn_sum.setText(_translate("mainWindow", "+"))
        self.btn_9.setText(_translate("mainWindow", "9"))
        self.btn_7.setText(_translate("mainWindow", "7"))
        self.btn_8.setText(_translate("mainWindow", "8"))
        self.btn_5.setText(_translate("mainWindow", "5"))
        self.btn_4.setText(_translate("mainWindow", "4"))
        self.btn_6.setText(_translate("mainWindow", "6"))
        self.btn_2.setText(_translate("mainWindow", "2"))
        self.btn_result.setText(_translate("mainWindow", "="))
        self.btn_1.setText(_translate("mainWindow", "1"))
        self.btn_3.setText(_translate("mainWindow", "3"))
        self.btn_0.setText(_translate("mainWindow", "0"))
        self.btn_dot.setText(_translate("mainWindow", "."))

    #====================My Functions================================

    # add parameter to the input
    def addParameter(self, parameter):
        former_text = (self.input.text()).strip(' ')
        new_text = former_text + str(parameter) + ' '
        self.input.setText(new_text)

    # calculate the result
    def result(self):

        try:
            # calculate expression with (+ , -)
            def sub_sum():
                counter = -1
                while True:
                    counter += 1
                    if string_lst[counter] == '+' or string_lst[counter] == '-':
                        if string_lst[counter] == '+':
                            new = float(string_lst[counter-1]) + float(string_lst[counter+1])
                        elif string_lst[counter] == '-':
                            new = float(string_lst[counter-1]) - float(string_lst[counter+1])
                        string_lst[counter] = new
                        string_lst.pop(counter - 1)
                        string_lst.pop(counter)
                        counter = -1
                        if len(string_lst) == 1:
                            break


            # calculate expression with (* , /)
            def mult_div():
                counter = -1
                while True:
                    counter += 1
                    if string_lst[counter] == '/' or string_lst[counter] == '*':
                        if string_lst[counter] == '/':
                            new = float(string_lst[counter-1]) / float(string_lst[counter+1])
                        elif string_lst[counter] == '*':
                            new = float(string_lst[counter-1]) * float(string_lst[counter+1])
                        string_lst[counter] = new
                        string_lst.pop(counter - 1)
                        string_lst.pop(counter)
                        counter = -1
                    if ('*' not in string_lst) and ('/' not in string_lst):
                        break



                if ('+' in string_lst) or ('-' in string_lst):
                    sub_sum()

                

                    
            
            # split the expression
            string = self.input.text()
            last = ''
            string_lst = []
            counter = -1
            for letter in string:
                counter += 1
                if (letter == '1') or (letter == '2') or (letter == '3') or (letter == '4') or (letter == '5') or (letter == '6') or (letter == '7') or (letter == '8') or (letter == '9') or (letter == '0') or (letter == '.'):
                    last += letter
                else:
                    string_lst.append(last)
                    if letter != ' ':
                        string_lst.append(letter)
                    last = ''


            # calculate the splited expression
            if ('*' in string_lst) or ('/' in string_lst):
                mult_div()
            else:
                sub_sum()

            # show the result
            self.input.setText(str(string_lst[0]))

        except:
            # syntax error
            self.input.setText('Syntax ERROR')
        


# run the app
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
